export const BASE_URL = 'http://localhost:4000'
export const API_URL = 'http://localhost:4000/api/v1'
export const ADMIN_ROLE = 'administrator'
export const TEACHER_ROLE = 'teacher'
export const STUDENT_ROLE = 'student'